name: Build Thunderz Runtime (Windows x64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Compile using g++ (64-bit)
      run: |
        mkdir build
        g++ -static -O2 ThunderzRuntime.cpp -o build/ThunderzRuntime.exe -lgdiplus -lgdi32 -luser32 -lkernel32

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: thunderz-windows-x64
        path: build/ThunderzRuntime.exe

